experiments/review/__init__.py
from flask import Blueprint

bp = Blueprint('review', __name__)

from . import routes

experiments/review/routes.py
from . import bp
from experiments import db
from experiments.models import Review
from flask import request, render_template, jsonify, send_file, Response, redirect, url_for, send_from_directory, send_from_directory

import json
import sys

@bp.route('/review') 
def showReview():
    # return "123"
    review = Review.query.order_by(Review.timestamp.desc()).all()

    return render_template("review/review.jinja", 
        review=review, 
        title='Review'
        )

@bp.route('/api/review', methods=['GET'])
def get_review():       
    
    ct = request.args.get('count')
    if not ct:
        ct = 50  
    
    return get_review_inner(ct)

def get_review_inner(ct):
    if not ct:
        ct = 50
    
    items = Review.query.order_by(Review.timestamp.desc()).limit(ct).all()
    
    response = jsonify([i.serialize for i in items])
    return response

@bp.route('/api/review', methods=['POST'])
def post_review(): 
    print('TronTron2' + request.get_data(as_text=True) , file=sys.stderr)

    data = json.loads(request.get_data(as_text=True))    
    name = data['name']
    comment = data['comment']
    score = data['score']
        
    id = addReviewItemInner(name, comment, score)
    if id:
        return jsonify({'res': 'Suc', 'id': id}) 
    else:
        return jsonify({'res': 'Error'})


@bp.route('/review/add/',methods=['POST'])
def addReviewItem():
    name = request.form['name']
    comment = request.form['comment']
    score = request.form['score']
    addReviewItemInner(name, comment, score)
    return redirect(url_for('review.showReview'))

def addReviewItemInner(name, comment, score):
    if not name or not name.strip():
        return False


    item = Review(username=name, comment=comment, score=score)
    db.session.add(item)
    db.session.commit()
    return item.id


@bp.route('/review/<int:item_id>/delete/', methods = ['GET','POST'])
def deleteReviewItem(item_id):
    item = Review.query.filter_by(id=item_id).one()
    db.session.delete(item)
    db.session.commit()
    return redirect(url_for('review.showReview'))

@bp.route('/review/deleteAll/', methods = ['GET','POST'])
def deleteReviewItemAll():
    deleteAllInner()
    return redirect(url_for('review.showReview'))

def deleteAllInner():
    db.session.query(Review).delete()
    db.session.commit()
    return True

experiments/templates/review/review.jinja
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block head %}
  {{ super() }}
  <script type="text/javascript">
    function confirmDeletaAll() {
      let ip = prompt('Please input the password to delete all');
      if(ip == '123') {
        location.href='{{ url_for('review.deleteReviewItemAll') }}';
      }        
    }
  </script>
{% endblock %}

{% block app_content %}


<form action="{{ url_for('review.addReviewItem') }}" method="post">
  <div class="form-inline">
    <input class="form-control" type="text" maxlength="100" name="name" placeholder="Name" autofocus value='Tron'>
    <input class="form-control" maxlength="100" name="comment" placeholder="Comment" value='Good game'>
    <input class="form-control" type='number' step='0.1' id='score' name="score" placeholder="4.0" value='4.0'>
    <button class="btn btn-primary mb-2" type="submit">Add</button>
    <button class="btn btn-primary mb-2" type="button" style='float:right;'
      onclick="confirmDeletaAll()">Remove
      All</button>
  </div>
</form>

<br>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Comment</th>
      <th scope="col">Score</th>
      <th scope="col">Time</th>
      <th scope="col">Operation</th>      
    </tr>
  </thead>
  <tbody>
    {% for item in review %}
    <tr>
      <td>{{item.username}}</td>
      <td>{{item.comment}}</td>
      <td>{{item.score}}</td>
      <td>{{item.timestamp}}</td>
      <td>
        <a href="{{url_for('review.deleteReviewItem', item_id = item.id )}}">Delete
        </a> 
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<script>
  document.getElementById('score').value = (Math.random() * 5).toFixed(1);
</script>
{% endblock %}